import { HTTPFacilitatorClient, type RoutesConfig } from "@x402/core/server";
import type { Network } from "@x402/core/types";
import { ExactEvmScheme } from "@x402/evm/exact/server";
import { paymentMiddleware, x402ResourceServer } from "@x402/express";
import express from "express";

const route = "/api/x402/official";
const config = {
  network: (process.env.X402_NETWORK ?? "eip155:84532") as Network,
  facilitatorUrl: process.env.X402_FACILITATOR_URL ?? "https://x402.org/facilitator",
  payTo:
    (process.env.X402_PAY_TO as `0x${string}` | undefined) ??
    "0x4a6aae28b27681856ae824af82fea87896ecc3ed",
  price: process.env.X402_PRICE ?? "$0.001",
};

const facilitatorClient = new HTTPFacilitatorClient({
  url: config.facilitatorUrl,
});

const resourceServer = new x402ResourceServer(facilitatorClient).register(
  config.network,
  new ExactEvmScheme(),
);

let initializationPromise: Promise<void> | null = null;

const initializeResourceServer = () => {
  if (initializationPromise) return initializationPromise;

  initializationPromise = (async () => {
    let lastError: unknown;

    for (let attempt = 1; attempt <= 3; attempt += 1) {
      try {
        await resourceServer.initialize();
        return;
      } catch (error) {
        lastError = error;
        if (attempt < 3) {
          await new Promise((resolve) => setTimeout(resolve, attempt * 250));
        }
      }
    }

    throw lastError;
  })().catch((error) => {
    initializationPromise = null;
    throw error;
  });

  return initializationPromise;
};

const routes: RoutesConfig = {
  [`GET ${route}`]: {
    accepts: {
      scheme: "exact",
      price: config.price,
      network: config.network,
      payTo: config.payTo!,
    },
    description: "A wallet-risk report protected by AgentPay Firewall policy controls.",
    mimeType: "application/json",
    serviceName: "AgentPay Firewall official x402 resource",
    unpaidResponseBody: () => ({
      contentType: "application/json",
      body: {
        error: "Payment required",
        integration: "official-x402",
        message:
          "This challenge is generated by @x402/express. Retry with PAYMENT-SIGNATURE to settle through the facilitator.",
        network: config.network,
        facilitatorUrl: config.facilitatorUrl,
      },
    }),
    settlementFailedResponseBody: (_context: unknown, settleResult: unknown) => ({
      contentType: "application/json",
      body: {
        error: "Settlement failed",
        integration: "official-x402",
        settleResult,
      },
    }),
  },
};

const app = express();

app.disable("x-powered-by");
app.set("trust proxy", true);
app.use((request, response, next) => {
  response.setHeader("Access-Control-Allow-Origin", "*");
  response.setHeader("Access-Control-Expose-Headers", "PAYMENT-REQUIRED, PAYMENT-RESPONSE");
  response.setHeader("Access-Control-Allow-Headers", "Accept, Content-Type, PAYMENT-SIGNATURE");
  response.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  response.setHeader("Cache-Control", "no-store");

  if (request.method === "OPTIONS") {
    response.status(204).end();
    return;
  }

  next();
});

app.use(route, async (_request, response, next) => {
  try {
    await initializeResourceServer();
    next();
  } catch {
    response.status(503).json({
      error: "x402 facilitator temporarily unavailable",
      integration: "official-x402",
    });
  }
});

app.use(paymentMiddleware(routes, resourceServer, undefined, undefined, false));

app.get(route, (_request, response) => {
  response.json({
    data: {
      reportId: "official_x402_risk_scan",
      summary: "Wallet has normal transfer patterns and no known sanctions exposure.",
      labels: ["low-risk", "official-x402", "base-sepolia"],
      confidence: 0.91,
    },
    integration: {
      protocol: "x402",
      implementation: "@x402/express",
      network: config.network,
      facilitatorUrl: config.facilitatorUrl,
      payTo: config.payTo,
      price: config.price,
    },
  });
});

export default app;
